# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stock_pb2 as stock__pb2


class SaveSharePriceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreStockDatabase = channel.stream_unary(
                '/usermgmt.SaveSharePrice/StoreStockDatabase',
                request_serializer=stock__pb2.StockPrice.SerializeToString,
                response_deserializer=stock__pb2.PriceResponse.FromString,
                )


class SaveSharePriceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreStockDatabase(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaveSharePriceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreStockDatabase': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreStockDatabase,
                    request_deserializer=stock__pb2.StockPrice.FromString,
                    response_serializer=stock__pb2.PriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usermgmt.SaveSharePrice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SaveSharePrice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreStockDatabase(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/usermgmt.SaveSharePrice/StoreStockDatabase',
            stock__pb2.StockPrice.SerializeToString,
            stock__pb2.PriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
