# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x08usermgmt\"*\n\nStockPrice\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04last\x18\x02 \x01(\t\"\x1f\n\rPriceResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t2Y\n\x0eSaveSharePrice\x12G\n\x12StoreStockDatabase\x12\x14.usermgmt.StockPrice\x1a\x17.usermgmt.PriceResponse\"\x00(\x01\x42\x19Z\x17wjuniorbh92/go-grpc-pocb\x06proto3')



_STOCKPRICE = DESCRIPTOR.message_types_by_name['StockPrice']
_PRICERESPONSE = DESCRIPTOR.message_types_by_name['PriceResponse']
StockPrice = _reflection.GeneratedProtocolMessageType('StockPrice', (_message.Message,), {
  'DESCRIPTOR' : _STOCKPRICE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:usermgmt.StockPrice)
  })
_sym_db.RegisterMessage(StockPrice)

PriceResponse = _reflection.GeneratedProtocolMessageType('PriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRICERESPONSE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:usermgmt.PriceResponse)
  })
_sym_db.RegisterMessage(PriceResponse)

_SAVESHAREPRICE = DESCRIPTOR.services_by_name['SaveSharePrice']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027wjuniorbh92/go-grpc-poc'
  _STOCKPRICE._serialized_start=25
  _STOCKPRICE._serialized_end=67
  _PRICERESPONSE._serialized_start=69
  _PRICERESPONSE._serialized_end=100
  _SAVESHAREPRICE._serialized_start=102
  _SAVESHAREPRICE._serialized_end=191
# @@protoc_insertion_point(module_scope)
