version: "3.9"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - ":50051:50051"
  client:
    build: ./client
    container_name: client
    depends_on:
      - server